In [1]:
import pandas as pd

In [8]:
#2016~2021の連結決算データを抽出
df_finance = pd.read_csv("./data/financial_data/finance_info_2016_2021.csv", encoding="shift_jis")
df_stock = pd.read_csv("./data/financial_data/stock_info_2016_2021_monthly.csv", encoding="shift_jis")

In [9]:
df_finance.head()

,日経会社コード,企業名称,決算期,決算種別,連結基準,<ヘッダー項目>決算月数,<ヘッダー項目>連結・単独フラグ,<ヘッダー項目>日経業種：コード,<ヘッダー項目>本社所在地：コード,<ヘッダー項目>本社所在地：日本語名称,...,<販売費及び一般管理費（四半期会計期間）>【販管費】開発費・試験研究費［３ヵ月］,<販売費及び一般管理費（四半期会計期間）>【販管費】保証修理費［３ヵ月］,<販売費及び一般管理費（四半期会計期間）>【販管費】その他販売費及び一般管理費［３ヵ月］,<販売費及び一般管理費（四半期会計期間）>【販管費】販売費及び一般管理費明細合計［３ヵ月］,<【更新中止】その他>従業員数（うち正社員）,<【更新中止】その他>従業員数（うち常勤嘱託）,<【更新中止】その他>従業員数（うち受入社員）,<【更新中止】その他>従業員数（うち休職者等）,<【更新中止】その他>従業員数（うち出向者）,<【更新中止】その他>従業員数（うちその他）
0,31504,リンクアンドモチベーション,2016/12,10,3,12,2,271704,13,東京都,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,31504,リンクアンドモチベーション,2016/12,10,1,12,2,271704,13,東京都,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,31504,リンクアンドモチベーション,2017/12,10,3,12,2,271704,13,東京都,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,31504,リンクアンドモチベーション,2017/12,10,1,12,2,271704,13,東京都,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,31504,リンクアンドモチベーション,2018/12,10,3,12,2,271704,13,東京都,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_stock.head()

,期間,日経平均,TOPIX,東証2部総合,東証マザーズ,JASDAQ,株式コード,上場コード,銘柄名称,時価総額（発行済み株式数ベース）,...,無償増資：割当率：親株比率,無償増資：割当率：子株比率,無償増資：割当日,無償増資：割当率,減資：発生フラグ,減資：割当率：親株比率,減資：割当率：子株比率,減資：確定日,減資：割当率,直近配当額
0,2016/01,17518.30,1432.07,4482.16,831.34,108.93,2170,11.0,リンクアンドモチベーション,1.300282e+10,...,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1.10
1,2016/02,16026.76,1297.85,4216.15,838.67,103.37,2170,11.0,リンクアンドモチベーション,1.345509e+10,...,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1.10
2,2016/03,16758.67,1347.20,4381.42,1020.80,110.02,2170,11.0,リンクアンドモチベーション,1.605566e+10,...,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1.25
3,2016/04,16666.05,1340.55,4292.72,1131.56,108.86,2170,11.0,リンクアンドモチベーション,1.594259e+10,...,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1.25
4,2016/05,17234.98,1379.80,4393.47,1144.64,113.88,2170,11.0,リンクアンドモチベーション,1.786474e+10,...,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1.25

In [15]:
print(df_finance.describe())

            日経会社コード   決算種別        連結基準  <ヘッダー項目>決算月数  <ヘッダー項目>連結・単独フラグ  \
count    413.000000  413.0  413.000000    413.000000             413.0
mean   28382.285714   10.0    1.251816     11.997579               2.0
std    12803.564051    0.0    0.664296      0.283004               0.0
min     1636.000000   10.0    1.000000      8.000000               2.0
25%    25965.000000   10.0    1.000000     12.000000               2.0
50%    31276.000000   10.0    1.000000     12.000000               2.0
75%    32249.000000   10.0    1.000000     12.000000               2.0
max    55192.000000   10.0    3.000000     16.000000               2.0

       <ヘッダー項目>日経業種：コード  <ヘッダー項目>本社所在地：コード  <基本項目>事業年度開始年月日［累計］  <基本項目>連結子会社数  \
count        413.000000         413.000000         4.130000e+02    390.000000
mean      269297.222760          14.656174         2.017709e+07     13.174359
std        16597.703749           5.192689         1.633419e+04     29.635235
min       133321.000000           3.000000         2.015020e+07      1.000000
25%       271704.000000          13.000000         2.016060e+07      2.000000
50%       271704.000000          13.000000         2.018030e+07      4.500000
75%       271704.000000          13.000000         2.019040e+07     11.000000
max       271704.000000          41.000000         2.020050e+07    255.000000

       <基本項目>連結子会社数（うち上場会社数）  ...  <販売費及び一般管理費（四半期会計期間）>【販管費】開発費・試験研究費［３ヵ月］  \
count              32.000000  ...                                       0.0
mean                2.250000  ...                                       NaN
std                 2.540003  ...                                       NaN
min                 1.000000  ...                                       NaN
25%                 1.000000  ...                                       NaN
50%                 1.000000  ...                                       NaN
75%                 2.000000  ...                                       NaN
max                 8.000000  ...                                       NaN

       <販売費及び一般管理費（四半期会計期間）>【販管費】保証修理費［３ヵ月］  \
count                                   0.0
mean                                    NaN
std                                     NaN
min                                     NaN
25%                                     NaN
50%                                     NaN
75%                                     NaN
max                                     NaN

       <販売費及び一般管理費（四半期会計期間）>【販管費】その他販売費及び一般管理費［３ヵ月］  \
count                                           0.0
mean                                            NaN
std                                             NaN
min                                             NaN
25%                                             NaN
50%                                             NaN
75%                                             NaN
max                                             NaN

       <販売費及び一般管理費（四半期会計期間）>【販管費】販売費及び一般管理費明細合計［３ヵ月］  <【更新中止】その他>従業員数（うち正社員）  \
count                                       5.000000                     0.0
mean                                     7147.600000                     NaN
std                                      9503.973422                     NaN
min                                       147.000000                     NaN
25%                                       229.000000                     NaN
50%                                       597.000000                     NaN
75%                                     14932.000000                     NaN
max                                     19833.000000                     NaN

       <【更新中止】その他>従業員数（うち常勤嘱託）  <【更新中止】その他>従業員数（うち受入社員）  \
count                      0.0                      0.0
mean                       NaN                      NaN
std                        NaN                      NaN
min                        NaN                      NaN
25%                        NaN                      NaN
50%                        NaN                      NaN
75%                        NaN                      NaN
max                        NaN                      NaN

       <【更新中止】その他>従業員数（うち休職者等）  <【更新中止】その他>従業員数（うち出向者）  <【更新中止】その他>従業員数（うちその他）
count                      0.0                     0.0                     0.0
mean                       NaN                     NaN                     NaN
std                        NaN                     NaN                     NaN
min                        NaN                     NaN                     NaN
25%                        NaN                     NaN                     NaN
50%                        NaN                     NaN                     NaN
75%                        NaN                     NaN                     NaN
max                        NaN                     NaN                     NaN

[8 rows x 167 columns]

In [16]:
print(df_finance.columns)

Index(['日経会社コード', '企業名称', '決算期', '決算種別', '連結基準', '<ヘッダー項目>決算月数',
       '<ヘッダー項目>連結・単独フラグ', '<ヘッダー項目>日経業種：コード', '<ヘッダー項目>本社所在地：コード',
       '<ヘッダー項目>本社所在地：日本語名称',
       ...
       '<販売費及び一般管理費（四半期会計期間）>【販管費】開発費・試験研究費［３ヵ月］',
       '<販売費及び一般管理費（四半期会計期間）>【販管費】保証修理費［３ヵ月］',
       '<販売費及び一般管理費（四半期会計期間）>【販管費】その他販売費及び一般管理費［３ヵ月］',
       '<販売費及び一般管理費（四半期会計期間）>【販管費】販売費及び一般管理費明細合計［３ヵ月］',
       '<【更新中止】その他>従業員数（うち正社員）', '<【更新中止】その他>従業員数（うち常勤嘱託）',
       '<【更新中止】その他>従業員数（うち受入社員）', '<【更新中止】その他>従業員数（うち休職者等）',
       '<【更新中止】その他>従業員数（うち出向者）', '<【更新中止】その他>従業員数（うちその他）'],
      dtype='object', length=170)

In [13]:
df_stock.describe()

,日経平均,TOPIX,東証2部総合,東証マザーズ,JASDAQ,株式コード,上場コード,時価総額（発行済み株式数ベース）,決算月,発行済み株式数（権利落ベース）,...,無償増資：割当率：親株比率,無償増資：割当率：子株比率,無償増資：割当日,無償増資：割当率,減資：発生フラグ,減資：割当率：親株比率,減資：割当率：子株比率,減資：確定日,減資：割当率,直近配当額
count,7906.000000,7906.000000,7906.000000,7906.000000,7906.000000,7906.000000,6010.000000,6.009000e+03,6010.000000,6.010000e+03,...,6010.0,6010.0,0.0,0.0,1.0,6010.000000,6010.000000,51.0,5.100000e+01,5994.000000
mean,21623.360299,1615.150746,6320.409851,1027.286866,152.921343,4792.576271,18.860233,2.175480e+11,5.502662,8.854219e+07,...,0.0,0.0,NaN,NaN,1.0,0.042429,0.008486,20170930.0,2.000000e-01,10.106737
std,3333.701084,171.203914,1026.304998,146.528149,24.251426,1717.369597,21.993110,9.361338e+11,3.797339,4.340849e+08,...,0.0,0.0,NaN,NaN,NaN,0.458673,0.091735,0.0,8.409527e-17,28.454638
min,15575.920000,1245.820000,4136.330000,620.090000,103.370000,2170.000000,11.000000,1.698000e+09,1.000000,7.055000e+05,...,0.0,0.0,NaN,NaN,1.0,0.000000,0.000000,20170930.0,2.000000e-01,0.000000
25%,19196.740000,1511.860000,5753.310000,907.560000,133.430000,3909.000000,11.000000,8.375270e+09,3.000000,6.781200e+06,...,0.0,0.0,NaN,NaN,1.0,0.000000,0.000000,20170930.0,2.000000e-01,0.000000
50%,21710.000000,1611.900000,6570.910000,1030.460000,155.290000,4301.000000,11.000000,2.106278e+10,3.000000,1.484220e+07,...,0.0,0.0,NaN,NaN,1.0,0.000000,0.000000,20170930.0,2.000000e-01,0.000000
75%,22977.130000,1753.290000,7213.640000,1150.060000,172.230000,4848.000000,14.000000,7.273930e+10,9.000000,3.848640e+07,...,0.0,0.0,NaN,NaN,1.0,0.000000,0.000000,20170930.0,2.000000e-01,12.950000
max,29178.800000,1954.000000,7678.150000,1313.380000,189.080000,9719.000000,92.000000,8.564635e+12,12.000000,4.787145e+09,...,0.0,0.0,NaN,NaN,1.0,5.000000,1.000000,20170930.0,2.000000e-01,1146.000000

In [14]:
df_stock.columns

Index(['期間', '日経平均', 'TOPIX', '東証2部総合', '東証マザーズ', 'JASDAQ', '株式コード', '上場コード',
       '銘柄名称', '時価総額（発行済み株式数ベース）', '決算月', '発行済み株式数（権利落ベース）', '日経平均採用区分',
       '日経３００採用区分', '日経５００採用区分', '東証：上場日', 'ジャスダック：上場日', '株式分割：発生フラグ',
       '株式分割：確定日', '株式分割：比率', '株式併合：発生フラグ', '株式併合：割当率：親株比率', '株式併合：割当率：子株比率',
       '株式併合：確定日', '有償増資：発生フラグ', '有償増資：割当率：親株比率', '有償増資：割当率：子株比率', '有償増資：割当日',
       '有償増資：払込期日', '無償増資：発生フラグ', '無償増資：割当率：親株比率', '無償増資：割当率：子株比率', '無償増資：割当日',
       '無償増資：割当率', '減資：発生フラグ', '減資：割当率：親株比率', '減資：割当率：子株比率', '減資：確定日',
       '減資：割当率', '直近配当額'],
      dtype='object')

日経会社コード                                                16552
企業名称                                                   16552
決算期                                                    16552
決算種別                                                   16552
連結基準                                                   16552
<基本項目>１株当たり利益［累計］                                      15924
<基本項目>１株当たり純資産                                         15923
<貸借対照表（資産）>流動資産                                        16511
<貸借対照表（負債）>流動負債                                        16511
<貸借対照表（純資産）>純資産合計／資本合計                                 16545
<貸借対照表（純資産）>株主資本                                       15667
<貸借対照表（純資産）>資本金                                        16422
<損益計算書（期首からの累計期間）>売上高・営業収益［累計］                         16519
<損益計算書（期首からの累計期間）>売上高・営業収益（うち金融収益）［累計］                   172
<損益計算書（期首からの累計期間）>営業費用［累計］                             16503
<損益計算書（期首からの累計期間）>売上原価・営業原価［累計］                        16369
<損益計算書（期首からの累計期間）>割賦販売未実現利益・返品調整引当金差額／返品調整引当金差額［累計］      517
<損益計算書（期首からの累計期間）>売上総利益［累計］                            16373
<損益計算書（期首からの累計期間）>販売費及び一般管理費［累計］                       16454
<損益計算書（期首からの累計期間）>金融費用［累計］                               135
<損益計算書（期首からの累計期間）>営業利益［累計］                             16480
<損益計算書（期首からの累計期間）>収益合計（性質別分類）［累計］                         18
<損益計算書（期首からの累計期間）>費用合計（性質別分類）［累計］                         18
<損益計算書（期首からの累計期間）>営業外収益［累計］                            15480
<損益計算書（期首からの累計期間）>受取利息・配当金［累計］                         14484
<損益計算書（期首からの累計期間）>有価証券売却益［累計］                            770
<損益計算書（期首からの累計期間）>有価証券評価益［累計］                            212
<損益計算書（期首からの累計期間）>デリバティブ評価益［累計］                          362
<損益計算書（期首からの累計期間）>その他資産処分益・評価益［累計］                      1638
<損益計算書（期首からの累計期間）>営業外費用［累計］                            15377
dtype: int64

,日経会社コード,決算種別,連結基準,<基本項目>１株当たり利益［累計］,<基本項目>１株当たり純資産,<貸借対照表（資産）>流動資産,<貸借対照表（負債）>流動負債,<貸借対照表（純資産）>純資産合計／資本合計,<貸借対照表（純資産）>株主資本,<貸借対照表（純資産）>資本金,...,<損益計算書（期首からの累計期間）>営業利益［累計］,<損益計算書（期首からの累計期間）>収益合計（性質別分類）［累計］,<損益計算書（期首からの累計期間）>費用合計（性質別分類）［累計］,<損益計算書（期首からの累計期間）>営業外収益［累計］,<損益計算書（期首からの累計期間）>受取利息・配当金［累計］,<損益計算書（期首からの累計期間）>有価証券売却益［累計］,<損益計算書（期首からの累計期間）>有価証券評価益［累計］,<損益計算書（期首からの累計期間）>デリバティブ評価益［累計］,<損益計算書（期首からの累計期間）>その他資産処分益・評価益［累計］,<損益計算書（期首からの累計期間）>営業外費用［累計］
count,16552.000000,16552.0,16552.000000,1.592400e+04,1.592300e+04,1.651100e+04,1.651100e+04,1.654500e+04,1.566700e+04,1.642200e+04,...,1.648000e+04,18.000000,18.000000,15480.000000,14484.000000,770.000000,212.000000,362.000000,1638.000000,15377.000000
mean,16356.983929,10.0,1.112917,2.856059e+04,6.492245e+05,1.750725e+05,1.260804e+05,1.546450e+05,1.089996e+05,1.841972e+04,...,1.822158e+04,306678.166667,258372.055556,2098.071382,1007.751243,2585.244156,373.641509,774.022099,941.351038,1827.600702
std,15188.218197,0.0,0.453236,1.829032e+06,4.134774e+07,9.492218e+05,8.806389e+05,6.728993e+05,5.222099e+05,8.929632e+04,...,8.432514e+04,227487.444488,191162.918373,10657.445471,6755.844422,13175.878543,1265.189210,4154.312953,4538.343569,9856.598468
min,1.000000,10.0,1.000000,-4.348150e+03,-1.448009e+04,6.900000e+01,1.600000e+01,-2.757040e+05,-5.529470e+05,1.000000e+00,...,-4.830100e+05,5303.000000,4724.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-5.000000
25%,1338.000000,10.0,1.000000,2.281000e+01,4.153600e+02,8.047500e+03,4.051500e+03,7.090000e+03,6.221000e+03,1.209000e+03,...,6.147500e+02,28049.000000,18411.250000,70.000000,19.000000,14.000000,13.000000,16.000000,14.000000,43.000000
50%,14787.000000,10.0,1.000000,6.525500e+01,9.182900e+02,2.483300e+04,1.295600e+04,2.375700e+04,2.035300e+04,3.652500e+03,...,2.306000e+03,410795.000000,363437.500000,262.500000,85.000000,62.000000,47.500000,72.000000,46.000000,161.000000
75%,30991.000000,10.0,1.000000,1.369925e+02,1.757875e+03,8.325300e+04,4.751250e+04,7.711900e+04,6.212050e+04,1.058600e+04,...,8.475500e+03,495058.000000,411715.250000,890.250000,345.000000,354.000000,166.500000,356.500000,231.000000,610.000000
max,91590.000000,10.0,3.000000,1.439162e+08,3.023400e+09,5.387864e+07,5.374407e+07,2.056521e+07,1.934815e+07,3.500000e+06,...,2.853971e+06,572359.000000,475083.000000,311186.000000,225495.000000,184949.000000,10875.000000,67132.000000,76123.000000,419975.000000