In [2]:
import pandas as pd

In [11]:
#2014~2019の連結決算データを抽出
df_data = pd.read_csv("demo_data.csv", encoding="shift_jis")
df_data.head()

,日経会社コード,企業名称,決算期,決算種別,連結基準,<基本項目>１株当たり利益［累計］,<基本項目>１株当たり純資産,<貸借対照表（資産）>流動資産,<貸借対照表（負債）>流動負債,<貸借対照表（純資産）>純資産合計／資本合計,...,<損益計算書（期首からの累計期間）>営業利益［累計］,<損益計算書（期首からの累計期間）>収益合計（性質別分類）［累計］,<損益計算書（期首からの累計期間）>費用合計（性質別分類）［累計］,<損益計算書（期首からの累計期間）>営業外収益［累計］,<損益計算書（期首からの累計期間）>受取利息・配当金［累計］,<損益計算書（期首からの累計期間）>有価証券売却益［累計］,<損益計算書（期首からの累計期間）>有価証券評価益［累計］,<損益計算書（期首からの累計期間）>デリバティブ評価益［累計］,<損益計算書（期首からの累計期間）>その他資産処分益・評価益［累計］,<損益計算書（期首からの累計期間）>営業外費用［累計］
0,1,極洋,2014/03,10,1,28.26,187.57,63033.0,41031.0,19930.0,...,2915.0,NaN,NaN,519.0,166.0,NaN,NaN,NaN,NaN,449.0
1,1,極洋,2015/03,10,1,23.17,215.65,69860.0,46460.0,23069.0,...,2460.0,NaN,NaN,674.0,199.0,NaN,NaN,NaN,NaN,1026.0
2,1,極洋,2016/03,10,1,17.13,214.97,70426.0,40835.0,23065.0,...,2433.0,NaN,NaN,698.0,114.0,NaN,NaN,NaN,NaN,317.0
3,1,極洋,2017/03,10,1,230.66,2378.09,72351.0,45195.0,25391.0,...,3723.0,NaN,NaN,764.0,100.0,NaN,NaN,NaN,NaN,779.0
4,1,極洋,2018/03,10,1,304.29,2679.00,81218.0,52100.0,29243.0,...,4066.0,NaN,NaN,809.0,104.0,NaN,NaN,NaN,NaN,438.0

In [12]:
df_data.columns

Index(['日経会社コード', '企業名称', '決算期', '決算種別', '連結基準', '<基本項目>１株当たり利益［累計］',
       '<基本項目>１株当たり純資産', '<貸借対照表（資産）>流動資産', '<貸借対照表（負債）>流動負債',
       '<貸借対照表（純資産）>純資産合計／資本合計', '<貸借対照表（純資産）>株主資本', '<貸借対照表（純資産）>資本金',
       '<損益計算書（期首からの累計期間）>売上高・営業収益［累計］',
       '<損益計算書（期首からの累計期間）>売上高・営業収益（うち金融収益）［累計］', '<損益計算書（期首からの累計期間）>営業費用［累計］',
       '<損益計算書（期首からの累計期間）>売上原価・営業原価［累計］',
       '<損益計算書（期首からの累計期間）>割賦販売未実現利益・返品調整引当金差額／返品調整引当金差額［累計］',
       '<損益計算書（期首からの累計期間）>売上総利益［累計］', '<損益計算書（期首からの累計期間）>販売費及び一般管理費［累計］',
       '<損益計算書（期首からの累計期間）>金融費用［累計］', '<損益計算書（期首からの累計期間）>営業利益［累計］',
       '<損益計算書（期首からの累計期間）>収益合計（性質別分類）［累計］',
       '<損益計算書（期首からの累計期間）>費用合計（性質別分類）［累計］', '<損益計算書（期首からの累計期間）>営業外収益［累計］',
       '<損益計算書（期首からの累計期間）>受取利息・配当金［累計］', '<損益計算書（期首からの累計期間）>有価証券売却益［累計］',
       '<損益計算書（期首からの累計期間）>有価証券評価益［累計］', '<損益計算書（期首からの累計期間）>デリバティブ評価益［累計］',
       '<損益計算書（期首からの累計期間）>その他資産処分益・評価益［累計］', '<損益計算書（期首からの累計期間）>営業外費用［累計］'],
      dtype='object')

In [18]:
print(df_data.count())
df_data.describe()

日経会社コード                                                16552
企業名称                                                   16552
決算期                                                    16552
決算種別                                                   16552
連結基準                                                   16552
<基本項目>１株当たり利益［累計］                                      15924
<基本項目>１株当たり純資産                                         15923
<貸借対照表（資産）>流動資産                                        16511
<貸借対照表（負債）>流動負債                                        16511
<貸借対照表（純資産）>純資産合計／資本合計                                 16545
<貸借対照表（純資産）>株主資本                                       15667
<貸借対照表（純資産）>資本金                                        16422
<損益計算書（期首からの累計期間）>売上高・営業収益［累計］                         16519
<損益計算書（期首からの累計期間）>売上高・営業収益（うち金融収益）［累計］                   172
<損益計算書（期首からの累計期間）>営業費用［累計］                             16503
<損益計算書（期首からの累計期間）>売上原価・営業原価［累計］                        16369
<損益計算書（期首からの累計期間）>割賦販売未実現利益・返品調整引当金差額／返品調整引当金差額［累計］      517
<損益計算書（期首からの累計期間）>売上総利益［累計］                            16373
<損益計算書（期首からの累計期間）>販売費及び一般管理費［累計］                       16454
<損益計算書（期首からの累計期間）>金融費用［累計］                               135
<損益計算書（期首からの累計期間）>営業利益［累計］                             16480
<損益計算書（期首からの累計期間）>収益合計（性質別分類）［累計］                         18
<損益計算書（期首からの累計期間）>費用合計（性質別分類）［累計］                         18
<損益計算書（期首からの累計期間）>営業外収益［累計］                            15480
<損益計算書（期首からの累計期間）>受取利息・配当金［累計］                         14484
<損益計算書（期首からの累計期間）>有価証券売却益［累計］                            770
<損益計算書（期首からの累計期間）>有価証券評価益［累計］                            212
<損益計算書（期首からの累計期間）>デリバティブ評価益［累計］                          362
<損益計算書（期首からの累計期間）>その他資産処分益・評価益［累計］                      1638
<損益計算書（期首からの累計期間）>営業外費用［累計］                            15377
dtype: int64

,日経会社コード,決算種別,連結基準,<基本項目>１株当たり利益［累計］,<基本項目>１株当たり純資産,<貸借対照表（資産）>流動資産,<貸借対照表（負債）>流動負債,<貸借対照表（純資産）>純資産合計／資本合計,<貸借対照表（純資産）>株主資本,<貸借対照表（純資産）>資本金,...,<損益計算書（期首からの累計期間）>営業利益［累計］,<損益計算書（期首からの累計期間）>収益合計（性質別分類）［累計］,<損益計算書（期首からの累計期間）>費用合計（性質別分類）［累計］,<損益計算書（期首からの累計期間）>営業外収益［累計］,<損益計算書（期首からの累計期間）>受取利息・配当金［累計］,<損益計算書（期首からの累計期間）>有価証券売却益［累計］,<損益計算書（期首からの累計期間）>有価証券評価益［累計］,<損益計算書（期首からの累計期間）>デリバティブ評価益［累計］,<損益計算書（期首からの累計期間）>その他資産処分益・評価益［累計］,<損益計算書（期首からの累計期間）>営業外費用［累計］
count,16552.000000,16552.0,16552.000000,1.592400e+04,1.592300e+04,1.651100e+04,1.651100e+04,1.654500e+04,1.566700e+04,1.642200e+04,...,1.648000e+04,18.000000,18.000000,15480.000000,14484.000000,770.000000,212.000000,362.000000,1638.000000,15377.000000
mean,16356.983929,10.0,1.112917,2.856059e+04,6.492245e+05,1.750725e+05,1.260804e+05,1.546450e+05,1.089996e+05,1.841972e+04,...,1.822158e+04,306678.166667,258372.055556,2098.071382,1007.751243,2585.244156,373.641509,774.022099,941.351038,1827.600702
std,15188.218197,0.0,0.453236,1.829032e+06,4.134774e+07,9.492218e+05,8.806389e+05,6.728993e+05,5.222099e+05,8.929632e+04,...,8.432514e+04,227487.444488,191162.918373,10657.445471,6755.844422,13175.878543,1265.189210,4154.312953,4538.343569,9856.598468
min,1.000000,10.0,1.000000,-4.348150e+03,-1.448009e+04,6.900000e+01,1.600000e+01,-2.757040e+05,-5.529470e+05,1.000000e+00,...,-4.830100e+05,5303.000000,4724.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-5.000000
25%,1338.000000,10.0,1.000000,2.281000e+01,4.153600e+02,8.047500e+03,4.051500e+03,7.090000e+03,6.221000e+03,1.209000e+03,...,6.147500e+02,28049.000000,18411.250000,70.000000,19.000000,14.000000,13.000000,16.000000,14.000000,43.000000
50%,14787.000000,10.0,1.000000,6.525500e+01,9.182900e+02,2.483300e+04,1.295600e+04,2.375700e+04,2.035300e+04,3.652500e+03,...,2.306000e+03,410795.000000,363437.500000,262.500000,85.000000,62.000000,47.500000,72.000000,46.000000,161.000000
75%,30991.000000,10.0,1.000000,1.369925e+02,1.757875e+03,8.325300e+04,4.751250e+04,7.711900e+04,6.212050e+04,1.058600e+04,...,8.475500e+03,495058.000000,411715.250000,890.250000,345.000000,354.000000,166.500000,356.500000,231.000000,610.000000
max,91590.000000,10.0,3.000000,1.439162e+08,3.023400e+09,5.387864e+07,5.374407e+07,2.056521e+07,1.934815e+07,3.500000e+06,...,2.853971e+06,572359.000000,475083.000000,311186.000000,225495.000000,184949.000000,10875.000000,67132.000000,76123.000000,419975.000000